"use strict";

const parts = [
  { id: 1, slug: "la-gota-que-lo-empieza-todo", title: "La gota que lo empieza todo", minutes: 95, question: "¿Qué es exactamente eso que huele, y por qué la planta lo fabrica?", achievement: "Saber qué hay en el frasco, de dónde viene y cómo acercarse a él con criterio.", published: true, modules: [[1, "Qué hay realmente dentro del frasco", 20], [2, "Por qué una planta fabrica su propio perfume", 25], [3, "Dónde vive el aroma: un mapa de la planta", 25], [4, "La primera regla: nunca puro sobre la piel", 25]] },
  { id: 2, slug: "aprender-a-leer-la-planta", title: "Aprender a leer la planta", minutes: 105, question: "¿Cómo reconocer y registrar la planta correcta?", achievement: "Identificar, documentar y conservar material vegetal útil.", published: true, modules: [[5, "Hoja, tallo y raíz: anatomía con un propósito", 30], [6, "Flor, fruto y semilla: dónde se concentra la esencia", 30], [7, "Llamar a cada planta por su nombre", 20], [8, "El herbario: tu archivo de referencia", 25]] },
  { id: 3, slug: "cultivar-y-cosechar-el-aroma", title: "Cultivar y cosechar el aroma", minutes: 95, question: "¿Qué decisiones de cultivo cambian lo que va a salir del alambique?", achievement: "Llevar una planta aromática desde el suelo hasta material seco listo para destilar.", published: true, modules: [[9, "Suelo, agua y abono: cultivar sin diluir el aroma", 25], [10, "Cortar para que rinda: poda y pinzado", 25], [11, "Defender el cultivo sin arruinar la cosecha", 20], [12, "Secar sin perder la esencia", 25]] },
  { id: 4, slug: "del-vegetal-a-la-esencia", title: "Del vegetal a la esencia", minutes: 175, question: "¿Cómo se separa el aroma de la planta?", achievement: "Describir un proceso de extracción completo y estimar su rendimiento.", published: true, modules: [[13, "Antes de encender nada: higiene y seguridad", 20], [14, "La física que hace posible el alambique", 25], [15, "Mezclas: todo lo que se puede separar", 25], [16, "Destilación: el corazón del oficio", 30], [17, "Vapor, vacío y fraccionamiento: elegir la destilación", 25], [18, "Cuando destilar no alcanza: disolventes, CO₂ y prensado", 25], [19, "¿Cuánto sale? Calcular el rendimiento", 25]] },
  { id: 5, slug: "reconocer-mezclar-y-usar", title: "Reconocer, mezclar y usar con criterio", minutes: 210, question: "¿Cómo sé que este aceite es bueno, y qué puedo hacer con él sin prometer lo que no puedo?", achievement: "Evaluar un aceite, diluirlo correctamente y construir una mezcla aromática.", modules: [[20, "La química del aroma en palabras simples", 25], [21, "Cromatografía: la huella digital de un aceite", 25], [22, "Calidad, adulteración y conservación", 20], [23, "Diluir bien: aceites vehiculares y proporciones", 25], [24, "El olfato, la memoria y un límite honesto", 25], [25, "Notas altas, medias y base: construir una fragancia", 25], [26, "Preparaciones cosméticas y ambientales", 25], [27, "El contacto: masaje con aceites esenciales", 20], [28, "Contraindicaciones: cuándo no", 20]] },
  { id: 6, slug: "del-aroma-al-emprendimiento", title: "Del aroma al emprendimiento", minutes: 70, question: "¿Puede esto sostenerse como actividad productiva?", achievement: "Evaluar con realismo un emprendimiento esenciero.", modules: [[29, "La esencia que nace como subproducto", 20], [30, "Ventajas y límites de la agroindustria esenciera", 25], [31, "Mercado, nichos y responsabilidad", 25]] }
];

module.exports = { parts };
